/********************************************************************************
** Form generated from reading UI file 'widget.ui'
**
** Created by: Qt User Interface Compiler version 6.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WIDGET_H
#define UI_WIDGET_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Widget
{
public:
    QPushButton *monthPick;
    QStackedWidget *dateStack;
    QWidget *page_3;
    QComboBox *yearIndex;
    QComboBox *monthIndex;
    QWidget *page_4;
    QComboBox *monthIndex1;
    QComboBox *yearIndex1;
    QComboBox *monthIndex2;
    QComboBox *yearIndex2;
    QLabel *label_24;
    QPushButton *searchButtion;
    QPushButton *durationPick;
    QStackedWidget *brandInfoStack;
    QWidget *page;
    QWidget *page_8;
    QLabel *hyundaiOnMonth;
    QLabel *hyundaiSales;
    QLabel *ds_2;
    QLabel *label_4;
    QLabel *label_2;
    QWidget *page_9;
    QLabel *kiaOnMonth;
    QLabel *kiaSales;
    QLabel *ds_3;
    QLabel *label_9;
    QLabel *label_10;
    QWidget *page_10;
    QLabel *genesisOnMonth;
    QLabel *genesisSales;
    QLabel *ds_4;
    QLabel *label_11;
    QLabel *label_12;
    QWidget *page_13;
    QLabel *chevorletOnMonth;
    QLabel *chevorletSales;
    QLabel *ds_5;
    QLabel *label_13;
    QLabel *label_14;
    QWidget *page_14;
    QLabel *kgOnMonth;
    QLabel *kgSales;
    QLabel *ds_6;
    QLabel *label_15;
    QLabel *label_16;
    QWidget *page_19;
    QLabel *renuaultOnMonth;
    QLabel *renaultSales;
    QLabel *ds_7;
    QLabel *label_17;
    QLabel *label_18;
    QWidget *page_20;
    QLabel *bmwOnMonth;
    QLabel *bmwSales;
    QLabel *ds_8;
    QLabel *label_19;
    QLabel *label_20;
    QWidget *page_7;
    QLabel *benzOnMonth;
    QLabel *benzSales;
    QLabel *ds_9;
    QLabel *label_21;
    QLabel *label_22;
    QWidget *page_21;
    QLabel *label_25;
    QLabel *label_23;
    QLabel *audiSales;
    QLabel *ds_10;
    QLabel *audiOnMonth;
    QWidget *page_22;
    QLabel *lexusOnMonth;
    QLabel *lexusSales;
    QLabel *ds_11;
    QLabel *label_26;
    QLabel *label_27;
    QWidget *page_2;
    QLabel *ds;
    QLabel *label_3;
    QLabel *label;
    QLabel *porscheSales;
    QLabel *porscheOnMonth;
    QWidget *page_23;
    QStackedWidget *contentStack;
    QWidget *page_17;
    QTableWidget *specificBrandTable;
    QWidget *page_18;
    QTableWidget *domesticTable;
    QTableWidget *overseasTable;

    void setupUi(QWidget *Widget)
    {
        if (Widget->objectName().isEmpty())
            Widget->setObjectName("Widget");
        Widget->resize(1003, 764);
        Widget->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        monthPick = new QPushButton(Widget);
        monthPick->setObjectName("monthPick");
        monthPick->setGeometry(QRect(140, 10, 111, 31));
        QFont font;
        font.setPointSize(13);
        font.setBold(true);
        monthPick->setFont(font);
        monthPick->setStyleSheet(QString::fromUtf8("color: rgb(11, 11, 11);\n"
"border: 2px solid;\n"
"border-color: rgb(143, 143, 143);"));
        dateStack = new QStackedWidget(Widget);
        dateStack->setObjectName("dateStack");
        dateStack->setGeometry(QRect(10, 50, 811, 61));
        dateStack->setStyleSheet(QString::fromUtf8("color: rgb(4, 4, 4);\n"
"border: 1px solid;\n"
"border-color: rgb(143, 143, 143);"));
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        yearIndex = new QComboBox(page_3);
        yearIndex->addItem(QString());
        yearIndex->setObjectName("yearIndex");
        yearIndex->setGeometry(QRect(330, 20, 72, 24));
        yearIndex->setStyleSheet(QString::fromUtf8("border: 1.2px solid;\n"
"border-color: rgb(150, 150, 150);"));
        monthIndex = new QComboBox(page_3);
        monthIndex->addItem(QString());
        monthIndex->addItem(QString());
        monthIndex->addItem(QString());
        monthIndex->addItem(QString());
        monthIndex->addItem(QString());
        monthIndex->addItem(QString());
        monthIndex->addItem(QString());
        monthIndex->addItem(QString());
        monthIndex->addItem(QString());
        monthIndex->addItem(QString());
        monthIndex->addItem(QString());
        monthIndex->addItem(QString());
        monthIndex->setObjectName("monthIndex");
        monthIndex->setGeometry(QRect(420, 20, 61, 24));
        monthIndex->setStyleSheet(QString::fromUtf8("border: 1.2px solid;\n"
"border-color: rgb(150, 150, 150);"));
        dateStack->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName("page_4");
        monthIndex1 = new QComboBox(page_4);
        monthIndex1->addItem(QString());
        monthIndex1->addItem(QString());
        monthIndex1->addItem(QString());
        monthIndex1->addItem(QString());
        monthIndex1->addItem(QString());
        monthIndex1->addItem(QString());
        monthIndex1->addItem(QString());
        monthIndex1->addItem(QString());
        monthIndex1->addItem(QString());
        monthIndex1->addItem(QString());
        monthIndex1->addItem(QString());
        monthIndex1->addItem(QString());
        monthIndex1->setObjectName("monthIndex1");
        monthIndex1->setGeometry(QRect(320, 20, 61, 24));
        monthIndex1->setStyleSheet(QString::fromUtf8("border: 1.2px solid;\n"
"border-color: rgb(139, 139, 139);"));
        yearIndex1 = new QComboBox(page_4);
        yearIndex1->addItem(QString());
        yearIndex1->setObjectName("yearIndex1");
        yearIndex1->setGeometry(QRect(240, 20, 72, 24));
        yearIndex1->setStyleSheet(QString::fromUtf8("border: 1.2px solid;\n"
"border-color: rgb(139, 139, 139);"));
        monthIndex2 = new QComboBox(page_4);
        monthIndex2->addItem(QString());
        monthIndex2->addItem(QString());
        monthIndex2->addItem(QString());
        monthIndex2->addItem(QString());
        monthIndex2->addItem(QString());
        monthIndex2->addItem(QString());
        monthIndex2->addItem(QString());
        monthIndex2->addItem(QString());
        monthIndex2->addItem(QString());
        monthIndex2->addItem(QString());
        monthIndex2->addItem(QString());
        monthIndex2->addItem(QString());
        monthIndex2->setObjectName("monthIndex2");
        monthIndex2->setGeometry(QRect(500, 20, 61, 24));
        monthIndex2->setStyleSheet(QString::fromUtf8("border: 1.2px solid;\n"
"border-color: rgb(139, 139, 139);"));
        yearIndex2 = new QComboBox(page_4);
        yearIndex2->addItem(QString());
        yearIndex2->setObjectName("yearIndex2");
        yearIndex2->setGeometry(QRect(420, 20, 72, 24));
        yearIndex2->setStyleSheet(QString::fromUtf8("border: 1.2px solid;\n"
"border-color: rgb(139, 139, 139);"));
        label_24 = new QLabel(page_4);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(390, 20, 21, 21));
        QFont font1;
        font1.setPointSize(14);
        font1.setBold(true);
        label_24->setFont(font1);
        label_24->setStyleSheet(QString::fromUtf8("border:0px;"));
        searchButtion = new QPushButton(page_4);
        searchButtion->setObjectName("searchButtion");
        searchButtion->setGeometry(QRect(570, 20, 61, 24));
        QFont font2;
        font2.setPointSize(11);
        searchButtion->setFont(font2);
        searchButtion->setStyleSheet(QString::fromUtf8("border:2px solid;\n"
"border-color: rgb(143, 143, 143);\n"
""));
        dateStack->addWidget(page_4);
        durationPick = new QPushButton(Widget);
        durationPick->setObjectName("durationPick");
        durationPick->setGeometry(QRect(590, 10, 111, 31));
        durationPick->setFont(font);
        durationPick->setStyleSheet(QString::fromUtf8("color: rgb(11, 11, 11);\n"
"border: 2px solid;\n"
"border-color: rgb(143, 143, 143);"));
        brandInfoStack = new QStackedWidget(Widget);
        brandInfoStack->setObjectName("brandInfoStack");
        brandInfoStack->setGeometry(QRect(9, 120, 811, 101));
        brandInfoStack->setStyleSheet(QString::fromUtf8("color: rgb(11, 11, 11);"));
        page = new QWidget();
        page->setObjectName("page");
        brandInfoStack->addWidget(page);
        page_8 = new QWidget();
        page_8->setObjectName("page_8");
        hyundaiOnMonth = new QLabel(page_8);
        hyundaiOnMonth->setObjectName("hyundaiOnMonth");
        hyundaiOnMonth->setGeometry(QRect(220, 60, 81, 20));
        hyundaiOnMonth->setFont(font2);
        hyundaiSales = new QLabel(page_8);
        hyundaiSales->setObjectName("hyundaiSales");
        hyundaiSales->setGeometry(QRect(220, 20, 51, 20));
        hyundaiSales->setFont(font2);
        hyundaiSales->setStyleSheet(QString::fromUtf8("color: rgb(11, 11, 11);"));
        ds_2 = new QLabel(page_8);
        ds_2->setObjectName("ds_2");
        ds_2->setGeometry(QRect(110, 20, 51, 20));
        ds_2->setFont(font2);
        ds_2->setStyleSheet(QString::fromUtf8("color: rgb(11, 11, 11);"));
        label_4 = new QLabel(page_8);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(110, 60, 81, 20));
        label_4->setFont(font2);
        label_4->setStyleSheet(QString::fromUtf8("color: rgb(11, 11, 11);"));
        label_2 = new QLabel(page_8);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(10, 10, 101, 81));
        label_2->setStyleSheet(QString::fromUtf8("border-image: url(:/resources/hyndai.gif);"));
        brandInfoStack->addWidget(page_8);
        page_9 = new QWidget();
        page_9->setObjectName("page_9");
        kiaOnMonth = new QLabel(page_9);
        kiaOnMonth->setObjectName("kiaOnMonth");
        kiaOnMonth->setGeometry(QRect(220, 60, 81, 20));
        kiaOnMonth->setFont(font2);
        kiaSales = new QLabel(page_9);
        kiaSales->setObjectName("kiaSales");
        kiaSales->setGeometry(QRect(220, 20, 51, 20));
        kiaSales->setFont(font2);
        ds_3 = new QLabel(page_9);
        ds_3->setObjectName("ds_3");
        ds_3->setGeometry(QRect(110, 20, 51, 20));
        ds_3->setFont(font2);
        label_9 = new QLabel(page_9);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(110, 60, 81, 20));
        label_9->setFont(font2);
        label_10 = new QLabel(page_9);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(10, 10, 101, 81));
        label_10->setStyleSheet(QString::fromUtf8("border-image: url(:/resources/kia.png);"));
        brandInfoStack->addWidget(page_9);
        page_10 = new QWidget();
        page_10->setObjectName("page_10");
        genesisOnMonth = new QLabel(page_10);
        genesisOnMonth->setObjectName("genesisOnMonth");
        genesisOnMonth->setGeometry(QRect(220, 60, 81, 20));
        genesisOnMonth->setFont(font2);
        genesisSales = new QLabel(page_10);
        genesisSales->setObjectName("genesisSales");
        genesisSales->setGeometry(QRect(220, 20, 51, 20));
        genesisSales->setFont(font2);
        ds_4 = new QLabel(page_10);
        ds_4->setObjectName("ds_4");
        ds_4->setGeometry(QRect(110, 20, 51, 20));
        ds_4->setFont(font2);
        label_11 = new QLabel(page_10);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(110, 60, 81, 20));
        label_11->setFont(font2);
        label_12 = new QLabel(page_10);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(10, 10, 101, 81));
        label_12->setStyleSheet(QString::fromUtf8("border-image: url(:/resources/genesis.png);"));
        brandInfoStack->addWidget(page_10);
        page_13 = new QWidget();
        page_13->setObjectName("page_13");
        chevorletOnMonth = new QLabel(page_13);
        chevorletOnMonth->setObjectName("chevorletOnMonth");
        chevorletOnMonth->setGeometry(QRect(220, 60, 81, 20));
        chevorletOnMonth->setFont(font2);
        chevorletSales = new QLabel(page_13);
        chevorletSales->setObjectName("chevorletSales");
        chevorletSales->setGeometry(QRect(220, 20, 51, 20));
        chevorletSales->setFont(font2);
        ds_5 = new QLabel(page_13);
        ds_5->setObjectName("ds_5");
        ds_5->setGeometry(QRect(110, 20, 51, 20));
        ds_5->setFont(font2);
        label_13 = new QLabel(page_13);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(110, 60, 81, 20));
        label_13->setFont(font2);
        label_14 = new QLabel(page_13);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(10, 10, 101, 81));
        label_14->setStyleSheet(QString::fromUtf8("border-image: url(:/resources/chevolet.png);"));
        brandInfoStack->addWidget(page_13);
        page_14 = new QWidget();
        page_14->setObjectName("page_14");
        kgOnMonth = new QLabel(page_14);
        kgOnMonth->setObjectName("kgOnMonth");
        kgOnMonth->setGeometry(QRect(220, 60, 81, 20));
        kgOnMonth->setFont(font2);
        kgSales = new QLabel(page_14);
        kgSales->setObjectName("kgSales");
        kgSales->setGeometry(QRect(220, 20, 51, 20));
        kgSales->setFont(font2);
        ds_6 = new QLabel(page_14);
        ds_6->setObjectName("ds_6");
        ds_6->setGeometry(QRect(110, 20, 51, 20));
        ds_6->setFont(font2);
        label_15 = new QLabel(page_14);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(110, 60, 81, 20));
        label_15->setFont(font2);
        label_16 = new QLabel(page_14);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(10, 10, 101, 81));
        label_16->setStyleSheet(QString::fromUtf8("border-image: url(:/resources/kg.png);"));
        brandInfoStack->addWidget(page_14);
        page_19 = new QWidget();
        page_19->setObjectName("page_19");
        renuaultOnMonth = new QLabel(page_19);
        renuaultOnMonth->setObjectName("renuaultOnMonth");
        renuaultOnMonth->setGeometry(QRect(220, 60, 81, 20));
        renuaultOnMonth->setFont(font2);
        renaultSales = new QLabel(page_19);
        renaultSales->setObjectName("renaultSales");
        renaultSales->setGeometry(QRect(220, 20, 51, 20));
        renaultSales->setFont(font2);
        ds_7 = new QLabel(page_19);
        ds_7->setObjectName("ds_7");
        ds_7->setGeometry(QRect(110, 20, 51, 20));
        ds_7->setFont(font2);
        label_17 = new QLabel(page_19);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(110, 60, 81, 20));
        label_17->setFont(font2);
        label_18 = new QLabel(page_19);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(10, 10, 101, 81));
        label_18->setStyleSheet(QString::fromUtf8("border-image: url(:/resources/renault.png);"));
        brandInfoStack->addWidget(page_19);
        page_20 = new QWidget();
        page_20->setObjectName("page_20");
        bmwOnMonth = new QLabel(page_20);
        bmwOnMonth->setObjectName("bmwOnMonth");
        bmwOnMonth->setGeometry(QRect(220, 60, 81, 20));
        bmwOnMonth->setFont(font2);
        bmwSales = new QLabel(page_20);
        bmwSales->setObjectName("bmwSales");
        bmwSales->setGeometry(QRect(220, 20, 51, 20));
        bmwSales->setFont(font2);
        ds_8 = new QLabel(page_20);
        ds_8->setObjectName("ds_8");
        ds_8->setGeometry(QRect(110, 20, 51, 20));
        ds_8->setFont(font2);
        label_19 = new QLabel(page_20);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(110, 60, 81, 20));
        label_19->setFont(font2);
        label_20 = new QLabel(page_20);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(10, 10, 101, 81));
        label_20->setStyleSheet(QString::fromUtf8("border-image: url(:/resources/bmw.png);"));
        brandInfoStack->addWidget(page_20);
        page_7 = new QWidget();
        page_7->setObjectName("page_7");
        benzOnMonth = new QLabel(page_7);
        benzOnMonth->setObjectName("benzOnMonth");
        benzOnMonth->setGeometry(QRect(220, 60, 81, 20));
        benzOnMonth->setFont(font2);
        benzSales = new QLabel(page_7);
        benzSales->setObjectName("benzSales");
        benzSales->setGeometry(QRect(220, 20, 51, 20));
        benzSales->setFont(font2);
        ds_9 = new QLabel(page_7);
        ds_9->setObjectName("ds_9");
        ds_9->setGeometry(QRect(110, 20, 51, 20));
        ds_9->setFont(font2);
        label_21 = new QLabel(page_7);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(110, 60, 81, 20));
        label_21->setFont(font2);
        label_22 = new QLabel(page_7);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(10, 10, 101, 81));
        label_22->setStyleSheet(QString::fromUtf8("border-image: url(:/resources/benz.png);"));
        brandInfoStack->addWidget(page_7);
        page_21 = new QWidget();
        page_21->setObjectName("page_21");
        label_25 = new QLabel(page_21);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(10, 10, 101, 81));
        label_25->setStyleSheet(QString::fromUtf8("border-image: url(:/resources/audi.png);"));
        label_23 = new QLabel(page_21);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(110, 60, 81, 20));
        label_23->setFont(font2);
        audiSales = new QLabel(page_21);
        audiSales->setObjectName("audiSales");
        audiSales->setGeometry(QRect(220, 20, 51, 20));
        audiSales->setFont(font2);
        ds_10 = new QLabel(page_21);
        ds_10->setObjectName("ds_10");
        ds_10->setGeometry(QRect(110, 20, 51, 20));
        ds_10->setFont(font2);
        audiOnMonth = new QLabel(page_21);
        audiOnMonth->setObjectName("audiOnMonth");
        audiOnMonth->setGeometry(QRect(220, 60, 81, 20));
        audiOnMonth->setFont(font2);
        brandInfoStack->addWidget(page_21);
        page_22 = new QWidget();
        page_22->setObjectName("page_22");
        lexusOnMonth = new QLabel(page_22);
        lexusOnMonth->setObjectName("lexusOnMonth");
        lexusOnMonth->setGeometry(QRect(220, 60, 81, 20));
        lexusOnMonth->setFont(font2);
        lexusSales = new QLabel(page_22);
        lexusSales->setObjectName("lexusSales");
        lexusSales->setGeometry(QRect(220, 20, 51, 20));
        lexusSales->setFont(font2);
        ds_11 = new QLabel(page_22);
        ds_11->setObjectName("ds_11");
        ds_11->setGeometry(QRect(110, 20, 51, 20));
        ds_11->setFont(font2);
        label_26 = new QLabel(page_22);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(110, 60, 81, 20));
        label_26->setFont(font2);
        label_27 = new QLabel(page_22);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(10, 10, 101, 81));
        label_27->setStyleSheet(QString::fromUtf8("border-image: url(:/resources/lexus.png);"));
        brandInfoStack->addWidget(page_22);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        ds = new QLabel(page_2);
        ds->setObjectName("ds");
        ds->setGeometry(QRect(110, 20, 51, 20));
        ds->setFont(font2);
        label_3 = new QLabel(page_2);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(110, 60, 81, 20));
        label_3->setFont(font2);
        label = new QLabel(page_2);
        label->setObjectName("label");
        label->setGeometry(QRect(10, 10, 101, 81));
        label->setStyleSheet(QString::fromUtf8("border-image: url(:/resources/porsche.png);"));
        porscheSales = new QLabel(page_2);
        porscheSales->setObjectName("porscheSales");
        porscheSales->setGeometry(QRect(220, 20, 51, 20));
        porscheSales->setFont(font2);
        porscheOnMonth = new QLabel(page_2);
        porscheOnMonth->setObjectName("porscheOnMonth");
        porscheOnMonth->setGeometry(QRect(220, 60, 81, 20));
        porscheOnMonth->setFont(font2);
        brandInfoStack->addWidget(page_2);
        page_23 = new QWidget();
        page_23->setObjectName("page_23");
        brandInfoStack->addWidget(page_23);
        contentStack = new QStackedWidget(Widget);
        contentStack->setObjectName("contentStack");
        contentStack->setGeometry(QRect(0, 230, 821, 521));
        page_17 = new QWidget();
        page_17->setObjectName("page_17");
        specificBrandTable = new QTableWidget(page_17);
        if (specificBrandTable->columnCount() < 3)
            specificBrandTable->setColumnCount(3);
        QFont font3;
        font3.setHintingPreference(QFont::PreferVerticalHinting);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        __qtablewidgetitem->setFont(font3);
        specificBrandTable->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        specificBrandTable->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        specificBrandTable->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        specificBrandTable->setObjectName("specificBrandTable");
        specificBrandTable->setGeometry(QRect(5, 0, 811, 521));
        specificBrandTable->setStyleSheet(QString::fromUtf8("color: rgb(11, 11, 11);"));
        specificBrandTable->setShowGrid(true);
        specificBrandTable->horizontalHeader()->setCascadingSectionResizes(false);
        specificBrandTable->horizontalHeader()->setDefaultSectionSize(190);
        specificBrandTable->horizontalHeader()->setHighlightSections(true);
        specificBrandTable->horizontalHeader()->setProperty("showSortIndicator", QVariant(false));
        specificBrandTable->horizontalHeader()->setStretchLastSection(true);
        specificBrandTable->verticalHeader()->setCascadingSectionResizes(false);
        specificBrandTable->verticalHeader()->setProperty("showSortIndicator", QVariant(false));
        specificBrandTable->verticalHeader()->setStretchLastSection(false);
        contentStack->addWidget(page_17);
        page_18 = new QWidget();
        page_18->setObjectName("page_18");
        domesticTable = new QTableWidget(page_18);
        if (domesticTable->columnCount() < 3)
            domesticTable->setColumnCount(3);
        QFont font4;
        font4.setPointSize(10);
        font4.setBold(true);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        __qtablewidgetitem3->setTextAlignment(Qt::AlignLeading|Qt::AlignVCenter);
        __qtablewidgetitem3->setFont(font4);
        domesticTable->setHorizontalHeaderItem(0, __qtablewidgetitem3);
        QFont font5;
        font5.setPointSize(10);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        __qtablewidgetitem4->setTextAlignment(Qt::AlignTrailing|Qt::AlignVCenter);
        __qtablewidgetitem4->setFont(font5);
        domesticTable->setHorizontalHeaderItem(1, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        __qtablewidgetitem5->setTextAlignment(Qt::AlignTrailing|Qt::AlignVCenter);
        __qtablewidgetitem5->setFont(font5);
        domesticTable->setHorizontalHeaderItem(2, __qtablewidgetitem5);
        domesticTable->setObjectName("domesticTable");
        domesticTable->setGeometry(QRect(5, 0, 811, 251));
        domesticTable->setStyleSheet(QString::fromUtf8("color: rgb(3, 3, 3);"));
        domesticTable->setShowGrid(true);
        domesticTable->horizontalHeader()->setCascadingSectionResizes(false);
        domesticTable->horizontalHeader()->setDefaultSectionSize(190);
        domesticTable->horizontalHeader()->setHighlightSections(true);
        domesticTable->horizontalHeader()->setProperty("showSortIndicator", QVariant(false));
        domesticTable->horizontalHeader()->setStretchLastSection(true);
        domesticTable->verticalHeader()->setCascadingSectionResizes(false);
        domesticTable->verticalHeader()->setProperty("showSortIndicator", QVariant(false));
        domesticTable->verticalHeader()->setStretchLastSection(false);
        overseasTable = new QTableWidget(page_18);
        if (overseasTable->columnCount() < 3)
            overseasTable->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        __qtablewidgetitem6->setTextAlignment(Qt::AlignLeading|Qt::AlignVCenter);
        __qtablewidgetitem6->setFont(font4);
        overseasTable->setHorizontalHeaderItem(0, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        __qtablewidgetitem7->setTextAlignment(Qt::AlignTrailing|Qt::AlignVCenter);
        __qtablewidgetitem7->setFont(font5);
        overseasTable->setHorizontalHeaderItem(1, __qtablewidgetitem7);
        QFont font6;
        font6.setPointSize(10);
        font6.setHintingPreference(QFont::PreferVerticalHinting);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        __qtablewidgetitem8->setTextAlignment(Qt::AlignTrailing|Qt::AlignVCenter);
        __qtablewidgetitem8->setFont(font6);
        overseasTable->setHorizontalHeaderItem(2, __qtablewidgetitem8);
        overseasTable->setObjectName("overseasTable");
        overseasTable->setGeometry(QRect(5, 270, 811, 251));
        overseasTable->setStyleSheet(QString::fromUtf8("color: rgb(3, 3, 3);"));
        overseasTable->setShowGrid(true);
        overseasTable->horizontalHeader()->setCascadingSectionResizes(false);
        overseasTable->horizontalHeader()->setDefaultSectionSize(190);
        overseasTable->horizontalHeader()->setHighlightSections(true);
        overseasTable->horizontalHeader()->setProperty("showSortIndicator", QVariant(false));
        overseasTable->horizontalHeader()->setStretchLastSection(true);
        overseasTable->verticalHeader()->setCascadingSectionResizes(false);
        overseasTable->verticalHeader()->setProperty("showSortIndicator", QVariant(false));
        overseasTable->verticalHeader()->setStretchLastSection(false);
        contentStack->addWidget(page_18);

        retranslateUi(Widget);
        QObject::connect(monthIndex, SIGNAL(currentIndexChanged(int)), Widget, SLOT(monthIndexChanged()));
        QObject::connect(searchButtion, SIGNAL(clicked()), Widget, SLOT(searchButtonClicked()));
        QObject::connect(durationPick, SIGNAL(clicked()), Widget, SLOT(durationPickButtonClicked()));
        QObject::connect(monthPick, SIGNAL(clicked()), Widget, SLOT(hyundaiButttonClicked()));

        dateStack->setCurrentIndex(0);
        brandInfoStack->setCurrentIndex(1);
        contentStack->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Widget);
    } // setupUi

    void retranslateUi(QWidget *Widget)
    {
        Widget->setWindowTitle(QCoreApplication::translate("Widget", "Widget", nullptr));
        monthPick->setText(QCoreApplication::translate("Widget", "\354\233\224 \354\204\240\355\203\235", nullptr));
        yearIndex->setItemText(0, QCoreApplication::translate("Widget", "2023\353\205\204", nullptr));

        monthIndex->setItemText(0, QCoreApplication::translate("Widget", "1\354\233\224", nullptr));
        monthIndex->setItemText(1, QCoreApplication::translate("Widget", "2\354\233\224", nullptr));
        monthIndex->setItemText(2, QCoreApplication::translate("Widget", "3\354\233\224", nullptr));
        monthIndex->setItemText(3, QCoreApplication::translate("Widget", "4\354\233\224", nullptr));
        monthIndex->setItemText(4, QCoreApplication::translate("Widget", "5\354\233\224", nullptr));
        monthIndex->setItemText(5, QCoreApplication::translate("Widget", "6\354\233\224", nullptr));
        monthIndex->setItemText(6, QCoreApplication::translate("Widget", "7\354\233\224", nullptr));
        monthIndex->setItemText(7, QCoreApplication::translate("Widget", "8\354\233\224", nullptr));
        monthIndex->setItemText(8, QCoreApplication::translate("Widget", "9\354\233\224", nullptr));
        monthIndex->setItemText(9, QCoreApplication::translate("Widget", "10\354\233\224", nullptr));
        monthIndex->setItemText(10, QCoreApplication::translate("Widget", "11\354\233\224", nullptr));
        monthIndex->setItemText(11, QCoreApplication::translate("Widget", "12\354\233\224", nullptr));

        monthIndex1->setItemText(0, QCoreApplication::translate("Widget", "1\354\233\224", nullptr));
        monthIndex1->setItemText(1, QCoreApplication::translate("Widget", "2\354\233\224", nullptr));
        monthIndex1->setItemText(2, QCoreApplication::translate("Widget", "3\354\233\224", nullptr));
        monthIndex1->setItemText(3, QCoreApplication::translate("Widget", "4\354\233\224", nullptr));
        monthIndex1->setItemText(4, QCoreApplication::translate("Widget", "5\354\233\224", nullptr));
        monthIndex1->setItemText(5, QCoreApplication::translate("Widget", "6\354\233\224", nullptr));
        monthIndex1->setItemText(6, QCoreApplication::translate("Widget", "7\354\233\224", nullptr));
        monthIndex1->setItemText(7, QCoreApplication::translate("Widget", "8\354\233\224", nullptr));
        monthIndex1->setItemText(8, QCoreApplication::translate("Widget", "9\354\233\224", nullptr));
        monthIndex1->setItemText(9, QCoreApplication::translate("Widget", "10\354\233\224", nullptr));
        monthIndex1->setItemText(10, QCoreApplication::translate("Widget", "11\354\233\224", nullptr));
        monthIndex1->setItemText(11, QCoreApplication::translate("Widget", "12\354\233\224", nullptr));

        yearIndex1->setItemText(0, QCoreApplication::translate("Widget", "2023\353\205\204", nullptr));

        monthIndex2->setItemText(0, QCoreApplication::translate("Widget", "1\354\233\224", nullptr));
        monthIndex2->setItemText(1, QCoreApplication::translate("Widget", "2\354\233\224", nullptr));
        monthIndex2->setItemText(2, QCoreApplication::translate("Widget", "3\354\233\224", nullptr));
        monthIndex2->setItemText(3, QCoreApplication::translate("Widget", "4\354\233\224", nullptr));
        monthIndex2->setItemText(4, QCoreApplication::translate("Widget", "5\354\233\224", nullptr));
        monthIndex2->setItemText(5, QCoreApplication::translate("Widget", "6\354\233\224", nullptr));
        monthIndex2->setItemText(6, QCoreApplication::translate("Widget", "7\354\233\224", nullptr));
        monthIndex2->setItemText(7, QCoreApplication::translate("Widget", "8\354\233\224", nullptr));
        monthIndex2->setItemText(8, QCoreApplication::translate("Widget", "9\354\233\224", nullptr));
        monthIndex2->setItemText(9, QCoreApplication::translate("Widget", "10\354\233\224", nullptr));
        monthIndex2->setItemText(10, QCoreApplication::translate("Widget", "11\354\233\224", nullptr));
        monthIndex2->setItemText(11, QCoreApplication::translate("Widget", "12\354\233\224", nullptr));

        yearIndex2->setItemText(0, QCoreApplication::translate("Widget", "2023\353\205\204", nullptr));

        label_24->setText(QCoreApplication::translate("Widget", "~", nullptr));
        searchButtion->setText(QCoreApplication::translate("Widget", "\354\241\260\355\232\214", nullptr));
        durationPick->setText(QCoreApplication::translate("Widget", "\352\270\260\352\260\204 \354\204\240\355\203\235", nullptr));
        hyundaiOnMonth->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        hyundaiSales->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        ds_2->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        label_4->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        label_2->setText(QString());
        kiaOnMonth->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        kiaSales->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        ds_3->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        label_9->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        label_10->setText(QString());
        genesisOnMonth->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        genesisSales->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        ds_4->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        label_11->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        label_12->setText(QString());
        chevorletOnMonth->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        chevorletSales->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        ds_5->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        label_13->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        label_14->setText(QString());
        kgOnMonth->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        kgSales->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        ds_6->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        label_15->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        label_16->setText(QString());
        renuaultOnMonth->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        renaultSales->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        ds_7->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        label_17->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        label_18->setText(QString());
        bmwOnMonth->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        bmwSales->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        ds_8->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        label_19->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        label_20->setText(QString());
        benzOnMonth->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        benzSales->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        ds_9->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        label_21->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        label_22->setText(QString());
        label_25->setText(QString());
        label_23->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        audiSales->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        ds_10->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        audiOnMonth->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        lexusOnMonth->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        lexusSales->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        ds_11->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        label_26->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        label_27->setText(QString());
        ds->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        label_3->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        label->setText(QString());
        porscheSales->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        porscheOnMonth->setText(QCoreApplication::translate("Widget", "\354\240\204\354\233\224 (\353\214\200\353\271\204)", nullptr));
        QTableWidgetItem *___qtablewidgetitem = specificBrandTable->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("Widget", "\353\252\250\353\215\270", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = specificBrandTable->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("Widget", "\355\214\220\353\247\244\353\237\211", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = specificBrandTable->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("Widget", "\354\240\220\354\234\240\354\234\250", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = domesticTable->horizontalHeaderItem(0);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("Widget", "\352\265\255\354\202\260\354\260\250", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = domesticTable->horizontalHeaderItem(1);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("Widget", "\354\264\235\355\225\251 : ", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = domesticTable->horizontalHeaderItem(2);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("Widget", "\353\214\200", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = overseasTable->horizontalHeaderItem(0);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("Widget", "\354\210\230\354\236\205\354\260\250", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = overseasTable->horizontalHeaderItem(1);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("Widget", "\354\264\235\355\225\251 :", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = overseasTable->horizontalHeaderItem(2);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("Widget", "\353\214\200", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Widget: public Ui_Widget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WIDGET_H
